name: tests/python

on:
  push:
    branches: [ RDBC-461 ]
  pull_request:
    branches: [ v5.0 ]
  schedule:
    - cron: '0 10 * * 6'


jobs:
    build:
      runs-on: ubuntu-latest

      env:
        RAVENDB_BUILD_TYPE: nightly
        RAVEN_License: ${{ secrets.RAVEN_LICENSE }}

      strategy:
        matrix:
          python-version: [ '3.7', '3.8', '3.9']
          serverVersion: [ "5.1", "5.2" ]
        fail-fast: false

      steps:
      - uses: actions/checkout@v2

      - name: Use Python ${{ matrix.node-version }}
        uses: actions/setup-python@v2
        with:
          python-version : ${{ matrix.python-version }}

      - name: Display Python version
        run:  python -c "import sys; print(sys.version)"

      - name: Set Date
        run: sudo date -s "01/01/2021 00:00:00"

      - name: Download RavenDB Server
        run: wget -q -O RavenDB.tar.bz2 "https://hibernatingrhinos.com/downloads/RavenDB%20for%20Linux%20x64/latest?buildType=${{ env.RAVENDB_BUILD_TYPE }}&version=${{ matrix.serverVersion }}"

      - name: Extract RavenDB Server
        run: tar xjf RavenDB.tar.bz2

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install client deps
        run: pip install -e .

      - name: Run RDB
        run: ./RavenDB/Server/Raven.Server -c $(realpath ./settings.json) &

      - name: Wait for server to run
        run: while ! curl http://127.0.0.1:8080; do sleep 0.2; echo "Waiting for server to start..."; done

      - name: Run tests
        run: python -m unittest discover